services:
  api:
    build:
      context: ./StudentManagementAPI
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=StudentManagementDB;User=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=True;
    restart: always
    networks:
      - student-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - student-network

networks:
  student-network:
    driver: bridge

volumes:
  sqlserver-data: